# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quMxpekunvSpBm6ORvxySI-ntavcLu0G
"""

!pip install requests

import requests
import json
import time
from datetime import datetime

url = "https://hacker-news.firebaseio.com/v0/topstories.json"
headers = {"User-Agent": "TrendPulse/1.0"}

categories = {
    "technology": ["ai", "software", "tech"],
    "worldnews": ["war", "government"],
    "sports": ["game", "team"],
    "science": ["research", "space"],
    "entertainment": ["movie", "music"]
}

stories = []
count = {cat: 0 for cat in categories}

import requests

url = "https://hacker-news.firebaseio.com/v0/topstories.json"

response = requests.get(url)
story_ids = response.json()[:500]

categories = {"technology": ["ai"]}

stories = []
count = {cat: 0 for cat in categories}

for sid in story_ids:
    res = requests.get(f"https://hacker-news.firebaseio.com/v0/item/{sid}.json")
    data = res.json()

    if not data:
        continue

    title = data.get("title", "").lower()

    if title == "":
        continue

for cat, keywords in categories.items():

    if any(word in title for word in keywords):

        if count[cat] >= 25:
            continue

        story_data = {
            "post_id": data.get("id"),
            "title": data.get("title"),
            "category": cat,
            "score": data.get("score", 0),
            "num_comments": data.get("descendants", 0),
            "author": data.get("by"),
            "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        stories.append(story_data)
        count[cat] += 1

        break